//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustainableChemistry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SustainableChemistry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider: John Wiley &amp; Sons, Ltd
        ///Content:text/plain; charset=&quot;UTF-8&quot;
        ///
        ///TY  - JOUR
        ///AU  - ILIA, G.
        ///AU  - CAPRITA, A.
        ///AU  - DEHELEAN, G.
        ///TI  - ChemInform Abstract: Synthesis of Tris(2-chloroethyl)phosphate.
        ///JO  - ChemInform
        ///JA  - ChemInform
        ///VL  - 27
        ///IS  - 5
        ///PB  - WILEY-VCH Verlag
        ///SN  - 1522-2667
        ///UR  - http://dx.doi.org/10.1002/chin.199605199
        ///DO  - 10.1002/chin.199605199
        ///SP  - no
        ///EP  - no
        ///KW  - organo-phosphorus compounds, acyclic O,N,S derivatives
        ///PY  - 1996
        ///AB  - ChemInform is a weekly Abst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10_1002_2Fchin_199605199 {
            get {
                return ResourceManager.GetString("_10_1002_2Fchin_199605199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] achs_jacsat105_661 {
            get {
                object obj = ResourceManager.GetObject("achs_jacsat105_661", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] achs_oprdfk4_175 {
            get {
                object obj = ResourceManager.GetObject("achs_oprdfk4_175", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BIB {
            get {
                object obj = ResourceManager.GetObject("BIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x0
        ///x1
        ///x2
        ///xp3
        ///xp4
        ///xp5
        ///xp6
        ///xp7
        ///xp8
        ///xp9
        ///xp10
        ///xc3
        ///xc4
        ///xpc4
        ///xch3
        ///xch4
        ///xch5
        ///xch6
        ///xch7
        ///xch8
        ///xch9
        ///xch10
        ///knotp
        ///xv0
        ///xv1
        ///xv2
        ///xvp3
        ///xvp4
        ///xvp5
        ///xvp6
        ///xvp7
        ///xvp8
        ///xvp9
        ///xvp10
        ///xvc3
        ///xvc4
        ///xvpc4
        ///xvch3
        ///xvch4
        ///xvch5
        ///xvch6
        ///xvch7
        ///xvch8
        ///xvch9
        ///xvch10
        ///knotpv
        ///k1
        ///k2
        ///k3
        ///ka1
        ///ka2
        ///ka3
        ///phia
        ///SsCH3
        ///SdCH2
        ///SssCH2
        ///StCH
        ///SdsCH
        ///SaaCH
        ///SsssCH
        ///SddC
        ///StsC
        ///SdssC
        ///SsaaC
        ///SaaaC
        ///SssssC
        ///SsNH2
        ///SdNH
        ///SssNH
        ///SaaNH
        ///StN
        ///SdsN
        ///SaaN
        ///SsssN
        ///SaaaN
        ///SsaaN
        ///SsNH3p
        ///SssNH2p
        ///SsssNHp
        ///SddNp
        ///StsNp
        ///SdNm
        ///Sdss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Descriptors {
            get {
                return ResourceManager.GetString("Descriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] europepmc {
            get {
                object obj = ResourceManager.GetObject("europepmc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] europepmc1 {
            get {
                object obj = ResourceManager.GetObject("europepmc1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As [+5 valence, one double bond]
        ///As [+5 valence, all single bonds]
        ///As [+5 valence, two double bonds]
        ///As [+3 valence, one double bond]
        ///As [+3 valence, all single bonds]
        ///As
        ///B
        ///-Br [aliphatic attach]
        ///-Br [aromatic attach]
        ///-Br [olefinic attach]
        ///-CH3 [aliphatic attach]
        ///-CH3 [aromatic attach]
        ///-CH2- [aliphatic attach]
        ///-CH2- [aromatic attach]
        ///-CH&lt; [aliphatic attach]
        ///-CH&lt; [aromatic attach]
        ///&gt;C&lt; [aliphatic attach]
        ///&gt;C&lt; [aromatic attach]
        ///=CH2 [aliphatic attach]
        ///-CH= [aromatic attach]
        ///=CH [aliphatic at [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fragments {
            get {
                return ResourceManager.GetString("Fragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACETALS		CO C(C)(C )OC		Aldehyde + Alcohol 	Acid		Hemi Acetyl	Water	4	CH3  AA	2	O    AA	1	&gt;C&lt;    AA						
        ///ACYLOINS		CC(=O)C(C)O	Acyloin condensation	carboxylic esters 	Base 		alph-hydroxyketone		2	CH3  AA	1	CH   AA	1	OH    AA	1	C=O   AA				
        ///ALCOHOLS		CO	Grignard	alkene + water	Acid 		alcohol 		1	CH3  AA	1	OH    AA								
        ///ALCOHOLS, ALLYLIC		C=CCO	Luche reduction/ Prins 	Keton + alkene 	Acid 	water	allylic alcohol		1	CH2  AA	1	OH    AA	1	C=CH  AA	1	C=CH2  AA				
        ///ALDEHYDES		[H]C(C)=O	Corey-Kim oxidation/S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Full_Functional_Group_List {
            get {
                return ResourceManager.GetString("Full_Functional_Group_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;style xmlns=&quot;http://purl.org/net/xbiblio/csl&quot; class=&quot;in-text&quot; version=&quot;1.0&quot; demote-non-dropping-particle=&quot;sort-only&quot; default-locale=&quot;en-GB&quot;&gt;
        ///  &lt;info&gt;
        ///    &lt;title&gt;Cite Them Right 10th edition - Harvard&lt;/title&gt;
        ///    &lt;id&gt;http://www.zotero.org/styles/harvard-cite-them-right&lt;/id&gt;
        ///    &lt;link href=&quot;http://www.zotero.org/styles/harvard-cite-them-right&quot; rel=&quot;self&quot;/&gt;
        ///    &lt;link href=&quot;http://www.zotero.org/styles/harvard-university-of-greenwich&quot; rel=&quot;template&quot;/&gt;
        ///    &lt;link hre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HarvardCiteThemRight {
            get {
                return ResourceManager.GetString("HarvardCiteThemRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string References1 {
            get {
                return ResourceManager.GetString("References1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S0040403900813763 {
            get {
                object obj = ResourceManager.GetObject("S0040403900813763", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S0040403900942163 {
            get {
                object obj = ResourceManager.GetObject("S0040403900942163", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S0040403901904617 {
            get {
                object obj = ResourceManager.GetObject("S0040403901904617", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S1001841712003142 {
            get {
                object obj = ResourceManager.GetObject("S1001841712003142", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
